Failed to load resource: the server responded with a status of 500 ()
hook.js:608 Error fetching local insider tips: ReferenceError: z is not defined
    at eval (mood-energy-optimizer-flow.ts:56:27)
    at (action-browser)/src/…rd/page.js?10:150:1)
    at __webpack_require__ (webpack-runtime.js?11:33:43)
    at (action-browser)/node…ard/page.js?12:40:1)
    at Object.__webpack_require__ [as require] (webpack-runtime.js?13:33:43)